{ config, pkgs, ... }:


let 
  unstable = import <nixpkgs-unstable> {config.allowUnfree = true;};
in

{
  # Home Manager needs a bit of information about you and the paths it should
  # manage. 
  home.username = "mbellani";
  home.homeDirectory = "/home/mbellani";

  # This value determines the Home Manager release that your configuration is
  # compatible with. This helps avoid breakage when a new Home Manager release
  # introduces backwards incompatible changes.
  #
  # You should not change this value, even if you update Home Manager. If you do
  # want to update the value, then make sure to first check the Home Manager
  # release notes.
  home.stateVersion = "22.11"; # Please read the comment before changing.  

  nixpkgs.config.allowUnfree = true;
  # The home.packages option allows you to install Nix packages into your
  # environment
  home.packages =  with pkgs; [
    # # Adds the 'hello' command to your environment. It prints a friendly
    # # "Hello, world!" when run.
    # pkgs.hello
    firefox
    git
    vim
    slack
    vscode
    alacritty
    rustup
    go
    ripgrep
    zsh
    tmux
    emacs
    _1password-gui
    chromium
    signal-desktop
    wakeonlan
    bat
    starship
  
    # Unstable packages, some latest versions of packages may not be available on the
    # stable channel.
    unstable.vivaldi
  

    # Add some system dependencies that are needed by programs like alacritty
    cmake
    pkg-config
    gcc
    
    
    # # It is sometimes useful to fine-tune packages, for example, by applying
    # # overrides. You can do that directly here, just don't forget the
    # # parentheses. Maybe you want to install Nerd Fonts with a limited number of
    # # fonts?
    # (pkgs.nerdfonts.override { fonts = [ "FantasqueSansMono" ]; })

    # # You can also create simple shell scripts directly inside your
    # # configuration. For example, this adds a command 'my-hello' to your
    # # environment:
    # (pkgs.writeShellScriptBin "my-hello" ''
    #   echo "Hello, ${config.home.username}!"
    # '')
  ];
  

  # Home Manager is pretty good at managing dotfiles. The primary way to manage
  # plain files is through 'home.file'.
  home.file = {
    # # Building this configuration will create a copy of 'dotfiles/screenrc' in
    # # the Nix store. Activating the configuration will then make '~/.screenrc' a
    # # symlink to the Nix store copy.
    # ".screenrc".source = dotfiles/screenrc;

    # # You can also set the file content immediately.
    # ".gradle/gradle.properties".text = ''
    #   org.gradle.console=verbose
    #   org.gradle.daemon.idletimeout=3600000
    # '';
  };

  # Manual sourcing of  `hm-session-vars` is not needed since i am managing my
  # shell (zsh in my case, not sure if that's true for other shells). `.zshenv`
  # generated by home-manager  already sources `~/.nix-profile/etc/profile.d/hm-session-vars.sh`.
  home.sessionVariables = {
     EDITOR = "code";
  };

  # Let Home Manager install and manage itself.
  programs.home-manager.enable = true;

  # Use nix modules to configure various packages
 
  #zsh
  programs.zsh = {
    enable = true;
    
    # configure oh-my-zsh
    oh-my-zsh = {
      enable = true;
      plugins = [ "git" ];
      theme = "robbyrussell";
    };

   # aliases
   shellAliases = {
     ssh="TERM=xterm-256color /usr/bin/ssh";
   };
  };

  
  # git
  programs.git = {
    enable = true;
    userName = "Manish Bellani";
    userEmail = "manish.bellani@gmail.com";

    extraConfig = {
      merge.tool = "code";

      core = {
        editor = "code";
      };     
       url = {
         "git@github.com:" = {
          insteadOf = "https://github.com";
         };
       };
    };
  };

  # starship
  programs.starship = {
     enable = true;
     enableZshIntegration = true;

     settings = {
      battery = {
        full_symbol = "🔋 ";
        charging_symbol = "⚡️ ";
        discharging_symbol = "💀 ";
      };
      
      battery.display = [
        { threshold = 10; style = "bold red"; }
        { threshold = 15; style = "red"; }
        { threshold = 20; style = "bold yellow"; }
        { threshold = 30; style = "yellow"; }
        { threshold = 100; style = "bold green"; }
      ];      
     };
     
  };
  # Allow gnome to see applications installed via home-manager
  targets.genericLinux.enable = true;
}
